### ISSUE TITLE
This model does not work on Replicate due to old cog

### ISSUE THREAD

**Issue by bdougie** [zeke/github-avatars#8]
Hey @zeke, I sent a Twitter DM with some more context yesterday. 

I have been exploring Replicate as a potential solution for future features at OpenSauced. I discovered this model on the explore page, but it presents the below error. I am still learning how all this works, but curious if there is an interest in getting to the working example on the site. 

<img width="1437" alt="Screen Shot 2023-01-04 at 10 43 27 PM" src="https://user-images.githubusercontent.com/5713670/210718401-6a617b27-edbe-4721-b07c-8a699a778947.png">

Also, FWIW would be happy to do content around this model and will continue to poke around.

**Comment by zeke** [comment]
Whoa! @bdougie! Been meaning to reach out to you. Yep I can get this working. Thanks for the shout. Please hold.

**Comment by zeke** [comment]
I pushed a new version to Replicate using a more recent version of [Cog](https://cog.run/)., and it's working again!

```json
{
  "username": "bdougie",
  "href": "https://github.com/bdougie.png",
  "prediction": "custom"
}
```

https://replicate.com/p/5q6x4z4pkvg5tnmjnhbcg27one

Note: Once it's [warmed up](https://replicate.com/docs/how-does-replicate-work#cold-boots), this model doesn't take long to run a prediction, but because it's not a popular model (and therefore not getting much traffic) your first request might take a while.
